//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Candidates) DeepCopyInto(out *Candidates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Candidates.
func (in *Candidates) DeepCopy() *Candidates {
	if in == nil {
		return nil
	}
	out := new(Candidates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelClaim) DeepCopyInto(out *ModelClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelClaim.
func (in *ModelClaim) DeepCopy() *ModelClaim {
	if in == nil {
		return nil
	}
	out := new(ModelClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelClaimList) DeepCopyInto(out *ModelClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelClaimList.
func (in *ModelClaimList) DeepCopy() *ModelClaimList {
	if in == nil {
		return nil
	}
	out := new(ModelClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelClaimSpec) DeepCopyInto(out *ModelClaimSpec) {
	*out = *in
	if in.MinTps != nil {
		in, out := &in.MinTps, &out.MinTps
		*out = new(float64)
		**out = **in
	}
	if in.EfficiencyPct != nil {
		in, out := &in.EfficiencyPct, &out.EfficiencyPct
		*out = new(int32)
		**out = **in
	}
	if in.MinComputeTFLOPS != nil {
		in, out := &in.MinComputeTFLOPS, &out.MinComputeTFLOPS
		*out = new(int64)
		**out = **in
	}
	if in.ExtraSelectors != nil {
		in, out := &in.ExtraSelectors, &out.ExtraSelectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelClaimSpec.
func (in *ModelClaimSpec) DeepCopy() *ModelClaimSpec {
	if in == nil {
		return nil
	}
	out := new(ModelClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelClaimStatus) DeepCopyInto(out *ModelClaimStatus) {
	*out = *in
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = new(ResolvedPhysics)
		**out = **in
	}
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(TemplateRef)
		**out = **in
	}
	if in.Candidates != nil {
		in, out := &in.Candidates, &out.Candidates
		*out = new(Candidates)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelClaimStatus.
func (in *ModelClaimStatus) DeepCopy() *ModelClaimStatus {
	if in == nil {
		return nil
	}
	out := new(ModelClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedPhysics) DeepCopyInto(out *ResolvedPhysics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedPhysics.
func (in *ResolvedPhysics) DeepCopy() *ResolvedPhysics {
	if in == nil {
		return nil
	}
	out := new(ResolvedPhysics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateRef) DeepCopyInto(out *TemplateRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateRef.
func (in *TemplateRef) DeepCopy() *TemplateRef {
	if in == nil {
		return nil
	}
	out := new(TemplateRef)
	in.DeepCopyInto(out)
	return out
}
